services:
  - type: web
    name: devblog
    env: python
    buildCommand: |
      pip install -r requirements.txt
      pip install -e .
    startCommand: gunicorn run:app
    envVars:
      - key: MONGO_USER
        sync: false
      - key: MONGO_PASSWORD
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: SECRET_KEY
        generateValue: true
    buildFilter:
      paths:
        - requirements.txt
        - DEV_BLOG/**
        - run.py
        - setup.py 